.TH UPGRADE-MAP-XML 1 "October 4, 2011"
.SH NAME
upgrade\-map\-xml \- program to convert stylesheets from Mapnik 0.* to the Mapnik 2.0 format
.SH SYNOPSIS
.B upgrade\-map\-xml
[ options ]
.I input-stylesheet
[ output-stylesheet ]
.SH DESCRIPTION
This manual page documents briefly the \fBupgrade\-map\-xml\fR command.
.PP
\fBupgrade\-map\-xml\fP is a program to convert the old Mapnik 0.* format stylesheets
to the new Mapnik2 format.
.SH OPTIONS
This program follows the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-\-indent
Indent the resulting XML.
.TP
.B \-\-in\-place
Update and overwrite the map in place.
.SH AUTHOR
This manual page was written by David Paleino <dapal@debian.org>, for the
Debian project (but may be used by others), and is licensed under the
terms of the GNU General Public License version 2 or, at your option,
any later version.
